2019-12-18 13:49:05,902 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:12: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-12-18 13:49:05,903 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:16: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-12-18 13:49:07,099 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:18: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-12-18 13:49:07,104 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:19: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

2019-12-18 13:49:07,119 WARNING tensorflow From main_train_and_test_adam_opt.py:101: The name tf.make_template is deprecated. Please use tf.compat.v1.make_template instead.

2019-12-18 13:49:07,124 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/data_generator.py:22: The name tf.FIFOQueue is deprecated. Please use tf.queue.FIFOQueue instead.

2019-12-18 13:49:07,132 WARNING tensorflow From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-12-18 13:49:07,132 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/SegCaps.py:27: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
2019-12-18 13:49:07,230 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a64115e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a64115e48>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:07,376 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a640e4b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a640e4b70>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:07,451 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a640bebe0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a640bebe0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:07,471 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:07,536 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:360: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-18 13:49:07,544 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:408: calling norm (from tensorflow.python.ops.linalg_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2019-12-18 13:49:07,662 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a640d1080>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a640d1080>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:07,736 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a640369e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a640369e8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:07,754 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:07,932 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a5c0db0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a5c0db0b8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:08,007 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a6407aef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a6407aef0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:08,024 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:08,202 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a405870b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a405870b8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:08,275 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a5c0e1fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a5c0e1fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:08,293 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:08,470 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a4047b0f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a4047b0f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:08,543 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a64016160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a64016160>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:08,560 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:08,737 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a4038c080>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a4038c080>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:08,810 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a4038ca90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a4038ca90>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:08,829 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:09,008 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a4038c160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a4038c160>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:09,082 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a5c0e1198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a5c0e1198>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:09,105 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f9a86b0f198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f9a86b0f198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:09,302 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a405874a8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a405874a8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:09,475 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a402baf60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a402baf60>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:09,493 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a86b0f198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:09,671 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a64082898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a64082898>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:09,744 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a64082d68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9a64082d68>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:09,768 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f9a7d9e96d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f9a7d9e96d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:09,965 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99d54235f8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99d54235f8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:10,040 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99d54236a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99d54236a0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:10,060 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a7d9e96d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a7d9e96d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:10,239 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99d5324048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99d5324048>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:10,313 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99d5488fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99d5488fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:10,338 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f9a7d9e96d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f9a7d9e96d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:10,536 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99d521c630>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99d521c630>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:10,610 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99d521c908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99d521c908>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:10,628 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a7d9e96d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f9a7d9e96d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:10,734 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/losses/semantic_segmentation_losses.py:56: calling softmax_cross_entropy_with_logits_v2_helper (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-18 13:49:10,807 WARNING tensorflow From main_train_and_test_adam_opt.py:140: The name tf.train.AdadeltaOptimizer is deprecated. Please use tf.compat.v1.train.AdadeltaOptimizer instead.

2019-12-18 13:49:14,770 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af9f9e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af9f9e80>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:14,847 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af7ddbe0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af7ddbe0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:14,916 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af7dd6d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af7dd6d8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:14,932 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:15,101 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af7a69e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af7a69e8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:15,169 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af771198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af771198>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:15,185 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:15,355 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af7e1b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af7e1b00>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:15,423 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af6ec0f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af6ec0f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:15,440 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:15,609 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af7d5630>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af7d5630>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:15,678 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af7d5630>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af7d5630>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:15,695 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:15,866 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af5e02b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af5e02b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:15,935 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af490400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af490400>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:15,951 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:16,120 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af5d9908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af5d9908>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:16,188 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af3c4a20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af3c4a20>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:16,205 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:16,372 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af3c40f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af3c40f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:16,440 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af3b96a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af3b96a0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:16,463 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f99af9f9e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f99af9f9e80>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:16,648 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af2a4400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af2a4400>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:16,716 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af3a6dd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af3a6dd8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:16,732 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:16,900 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af351908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af351908>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:16,969 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af1b50b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af1b50b8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:16,992 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f99af9f9e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f99af9f9e80>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:17,178 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af086588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af086588>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:17,247 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af001a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af001a90>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:17,263 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:17,431 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af24a780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af24a780>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:17,498 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99aefbf208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99aefbf208>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:17,521 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f99af9f9e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f99af9f9e80>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:17,835 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af1a5710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af1a5710>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:17,903 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af1a5f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f99af1a5f98>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:49:17,919 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f99af9f9e80>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:49:18,078 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:44: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.

2019-12-18 13:49:18,079 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:47: The name tf.metrics.mean is deprecated. Please use tf.compat.v1.metrics.mean instead.

2019-12-18 13:49:18,832 INFO numexpr.utils NumExpr defaulting to 4 threads.
2019-12-18 13:49:19,812 WARNING tensorflow 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

2019-12-18 13:49:19,814 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:48: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2019-12-18 13:49:25,458 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:58: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
2019-12-18 13:49:25,458 WARNING tensorflow `tf.train.start_queue_runners()` was called when no queue runners were defined. You can safely remove the call to this deprecated function.
2019-12-18 13:49:25,461 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:47: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

2019-12-18 13:49:26,162 WARNING tensorflow From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1282: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-12-18 13:49:26,166 INFO tensorflow Restoring parameters from ./Experiments/SegCaps_multilabels_2019-11-09_01-25-53/weights/model-90000
2019-12-18 13:49:27,487 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:192: The name tf.train.GradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.GradientDescentOptimizer instead.

2019-12-18 13:49:27,487 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:194: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

2019-12-18 13:49:27,487 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:196: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

2019-12-18 13:52:01,722 ERROR root Error at tf
Traceback (most recent call last):
  File "main_train_and_test_adam_opt.py", line 327, in <module>
    loop.run()
  File "./Lung_Segmentation/tensorflow_train/train_loop.py", line 219, in run
    self.test()
  File "main_train_and_test_adam_opt.py", line 203, in test
    feed_dict=feed_dict)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
KeyboardInterrupt
2019-12-18 13:52:50,817 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:12: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-12-18 13:52:50,817 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:16: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-12-18 13:52:50,972 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:18: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-12-18 13:52:50,974 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:19: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

2019-12-18 13:52:50,985 WARNING tensorflow From main_train_and_test_adam_opt.py:101: The name tf.make_template is deprecated. Please use tf.compat.v1.make_template instead.

2019-12-18 13:52:50,987 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/data_generator.py:22: The name tf.FIFOQueue is deprecated. Please use tf.queue.FIFOQueue instead.

2019-12-18 13:52:50,992 WARNING tensorflow From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-12-18 13:52:50,992 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/SegCaps.py:27: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
2019-12-18 13:52:51,079 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f989813fef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f989813fef0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:52:51,168 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98981670b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98981670b8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:52:51,242 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f989810bb00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f989810bb00>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:52:51,258 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:52:51,316 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:361: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-18 13:52:51,322 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:409: calling norm (from tensorflow.python.ops.linalg_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2019-12-18 13:55:54,637 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f989803d7f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f989803d7f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:55:54,710 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f989803d7f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f989803d7f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:55:54,726 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:55:57,761 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98980afc18>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98980afc18>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:55:57,834 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f984034ee48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f984034ee48>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:55:57,851 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:55:59,025 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f985c111860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f985c111860>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:55:59,099 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f985c111c88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f985c111c88>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:55:59,116 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:00,464 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98402d6f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98402d6f60>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:00,539 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98400e3710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98400e3710>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:00,557 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:01,458 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98400e0588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98400e0588>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:01,533 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f984013bcc0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f984013bcc0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:01,550 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:02,282 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f984013bda0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f984013bda0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:02,355 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98400f0518>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98400f0518>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:02,380 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f989813ff60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f989813ff60>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:03,021 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c4f3550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c4f3550>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:03,094 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c4f3a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c4f3a58>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:03,112 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f989813ff60>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:03,674 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c4976d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c4976d8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:03,746 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c497b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c497b38>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:03,770 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f989813ff60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f989813ff60>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:04,413 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c14f2e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c14f2e8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:04,487 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c144710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c144710>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:04,505 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f985c0f5f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f985c0f5f98>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:05,212 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c3b9fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c3b9fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:05,285 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98400900b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f98400900b8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:05,310 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f985c0f5f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f985c0f5f98>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:05,974 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c71d3c8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c71d3c8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:06,048 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c64ed68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f980c64ed68>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:06,066 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f985c0f5f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f985c0f5f98>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:06,626 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/losses/semantic_segmentation_losses.py:56: calling softmax_cross_entropy_with_logits_v2_helper (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-18 13:56:06,681 WARNING tensorflow From main_train_and_test_adam_opt.py:140: The name tf.train.AdadeltaOptimizer is deprecated. Please use tf.compat.v1.train.AdadeltaOptimizer instead.

2019-12-18 13:56:10,574 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f5994278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f5994278>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:10,653 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57e88d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57e88d0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:10,722 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57e80f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57e80f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:10,739 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:32,554 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f578ea58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f578ea58>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:32,623 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f578e8d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f578e8d0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:32,639 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:34,906 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57ab048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57ab048>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:34,974 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57ab080>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57ab080>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:34,990 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:35,633 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57df048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57df048>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:35,702 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57dff60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57dff60>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:35,718 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:36,330 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f54ee208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f54ee208>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:36,398 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f54ee588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f54ee588>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:36,415 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:37,040 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f5365eb8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f5365eb8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:37,109 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f5365da0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f5365da0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:37,125 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:37,719 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f51b9748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f51b9748>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:37,788 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f51d1dd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f51d1dd8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:37,811 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f97f5994278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f97f5994278>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:38,429 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f4ef86a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f4ef86a0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:38,498 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57a3400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f57a3400>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:38,515 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:39,104 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f50a8240>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f50a8240>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:39,177 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f536de80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f536de80>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:39,201 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f97f5994278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f97f5994278>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:39,811 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f6ea4198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f6ea4198>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:39,880 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f51e6a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f51e6a58>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:39,896 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:40,514 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f5268940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f5268940>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:40,585 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f6eda668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f6eda668>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:40,608 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f97f5994278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f97f5994278>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:41,204 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f4c4d630>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f4c4d630>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:41,272 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f4ef8588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f97f4ef8588>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 13:56:41,288 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f97f5994278>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 13:56:41,888 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:44: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.

2019-12-18 13:56:41,889 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:47: The name tf.metrics.mean is deprecated. Please use tf.compat.v1.metrics.mean instead.

2019-12-18 13:56:42,139 INFO numexpr.utils NumExpr defaulting to 4 threads.
2019-12-18 13:56:42,456 WARNING tensorflow 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

2019-12-18 13:56:42,457 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:48: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2019-12-18 13:56:45,605 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:58: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
2019-12-18 13:56:45,605 WARNING tensorflow `tf.train.start_queue_runners()` was called when no queue runners were defined. You can safely remove the call to this deprecated function.
2019-12-18 13:56:45,607 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:47: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

2019-12-18 13:56:46,249 WARNING tensorflow From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1282: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-12-18 13:56:46,250 INFO tensorflow Restoring parameters from ./Experiments/SegCaps_multilabels_2019-11-09_01-25-53/weights/model-90000
2019-12-18 13:56:47,068 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:192: The name tf.train.GradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.GradientDescentOptimizer instead.

2019-12-18 13:56:47,069 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:194: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

2019-12-18 13:56:47,069 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:196: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

2019-12-18 13:59:07,086 ERROR root Error at tf
Traceback (most recent call last):
  File "main_train_and_test_adam_opt.py", line 327, in <module>
    loop.run()
  File "./Lung_Segmentation/tensorflow_train/train_loop.py", line 219, in run
    self.test()
  File "main_train_and_test_adam_opt.py", line 203, in test
    feed_dict=feed_dict)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/bdb.py", line 55, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/bdb.py", line 99, in dispatch_return
    if self.quitting: raise BdbQuit
bdb.BdbQuit
2019-12-18 14:01:45,676 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:12: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-12-18 14:01:45,676 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:16: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-12-18 14:01:45,865 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:18: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-12-18 14:01:45,866 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:19: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

2019-12-18 14:01:45,878 WARNING tensorflow From main_train_and_test_adam_opt.py:101: The name tf.make_template is deprecated. Please use tf.compat.v1.make_template instead.

2019-12-18 14:01:45,880 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/data_generator.py:22: The name tf.FIFOQueue is deprecated. Please use tf.queue.FIFOQueue instead.

2019-12-18 14:01:45,885 WARNING tensorflow From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-12-18 14:01:45,885 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/SegCaps.py:27: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
2019-12-18 14:01:45,972 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f25ec149ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f25ec149ef0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 14:01:46,062 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f25ec173f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f25ec173f98>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 14:01:46,135 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f25ec173f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f25ec173f98>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 14:01:46,152 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f25ec149f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f25ec149f60>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 14:01:46,209 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:361: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-18 14:01:46,216 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:409: calling norm (from tensorflow.python.ops.linalg_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2019-12-18 14:13:50,935 ERROR root Error at tf
Traceback (most recent call last):
  File "main_train_and_test_adam_opt.py", line 327, in <module>
    loop.run()
  File "./Lung_Segmentation/tensorflow_train/train_loop.py", line 206, in run
    self.init_all()
  File "./Lung_Segmentation/tensorflow_train/train_loop.py", line 134, in init_all
    self.initNetworks()
  File "main_train_and_test_adam_opt.py", line 108, in initNetworks
    prediction = training_net(data,num_labels=self.num_labels,is_training=True, data_format=self.data_format)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 392, in __call__
    return self._call_func(args, kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 354, in _call_func
    result = self._func(*args, **kwargs)
  File "./Lung_Segmentation/LungSeg/SegCaps/SegCaps.py", line 38, in SegCaps_multilabels
    routings=1, name='primarycaps',is_training=is_training)(conv1_reshaped)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 636, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 146, in wrapper
    ), args, kwargs)
tensorflow.python.autograph.impl.api.StagingError: in converted code:

    ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:165 call
        num_routing=self.routings)
    ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:396 update_routing
        swap_memory=True)
    /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py:3501 while_loop
        return_same_structure)
    /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py:3012 BuildLoop
        pred, body, original_loop_vars, loop_vars, shape_invariants)
    /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py:2937 _BuildLoop
        body_result = body(*packed_vars_for_body)
    ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:377 _body
        tf.print("mean logit:", mean_logit, output_stream=sys.stdout)
    ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:377 _body
        tf.print("mean logit:", mean_logit, output_stream=sys.stdout)
    /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/bdb.py:51 trace_dispatch
        return self.dispatch_line(frame)
    /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/bdb.py:70 dispatch_line
        if self.quitting: raise BdbQuit

    BdbQuit: 


originally defined at:
  File "main_train_and_test_adam_opt.py", line 101, in initNetworks
    training_net = tf.make_template('net', self.network)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 160, in make_template
    **kwargs)

2019-12-18 14:16:18,575 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:12: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-12-18 14:16:18,575 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:16: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-12-18 14:16:18,721 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:18: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-12-18 14:16:18,722 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:19: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

2019-12-18 14:16:18,731 WARNING tensorflow From main_train_and_test_adam_opt.py:93: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.

2019-12-18 14:16:18,731 ERROR root Error at tf
Traceback (most recent call last):
  File "main_train_and_test_adam_opt.py", line 328, in <module>
    loop.run()
  File "./Lung_Segmentation/tensorflow_train/train_loop.py", line 206, in run
    self.init_all()
  File "./Lung_Segmentation/tensorflow_train/train_loop.py", line 134, in init_all
    self.initNetworks()
  File "main_train_and_test_adam_opt.py", line 93, in initNetworks
    tf.enable_eager_execution()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5878, in enable_eager_execution
    server_def=None)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5936, in enable_eager_execution_internal
    "tf.enable_eager_execution must be called at program startup.")
ValueError: tf.enable_eager_execution must be called at program startup.
2019-12-18 14:21:45,086 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:12: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-12-18 14:21:45,086 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:16: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-12-18 14:21:45,272 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:18: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-12-18 14:21:45,274 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:19: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

2019-12-18 14:21:45,285 WARNING tensorflow From main_train_and_test_adam_opt.py:102: The name tf.make_template is deprecated. Please use tf.compat.v1.make_template instead.

2019-12-18 14:21:45,287 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/data_generator.py:22: The name tf.FIFOQueue is deprecated. Please use tf.queue.FIFOQueue instead.

2019-12-18 14:21:45,292 WARNING tensorflow From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-12-18 14:21:45,292 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/SegCaps.py:27: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
2019-12-18 14:21:45,379 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe7580cce80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe7580cce80>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 14:21:45,467 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe7580f9128>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe7580f9128>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 14:21:45,540 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe75801cf60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe75801cf60>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 14:21:45,557 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7fe7580ccef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7fe7580ccef0>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 14:21:45,613 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:361: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-18 14:21:45,620 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:409: calling norm (from tensorflow.python.ops.linalg_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2019-12-18 14:26:11,253 WARNING tensorflow From <stdin>:1: Print (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2018-08-20.
Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:
```python
    sess = tf.compat.v1.Session()
    with sess.as_default():
        tensor = tf.range(10)
        print_op = tf.print(tensor)
        with tf.control_dependencies([print_op]):
          out = tf.add(tensor, tensor)
        sess.run(out)
    ```
Additionally, to use tf.print in python 2.7, users must make sure to import
the following:

  `from __future__ import print_function`

2019-12-18 14:27:05,327 ERROR root Error at tf
Traceback (most recent call last):
  File "main_train_and_test_adam_opt.py", line 328, in <module>
    loop.run()
  File "./Lung_Segmentation/tensorflow_train/train_loop.py", line 206, in run
    self.init_all()
  File "./Lung_Segmentation/tensorflow_train/train_loop.py", line 134, in init_all
    self.initNetworks()
  File "main_train_and_test_adam_opt.py", line 109, in initNetworks
    prediction = training_net(data,num_labels=self.num_labels,is_training=True, data_format=self.data_format)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 392, in __call__
    return self._call_func(args, kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 354, in _call_func
    result = self._func(*args, **kwargs)
  File "./Lung_Segmentation/LungSeg/SegCaps/SegCaps.py", line 38, in SegCaps_multilabels
    routings=1, name='primarycaps',is_training=is_training)(conv1_reshaped)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 636, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 146, in wrapper
    ), args, kwargs)
tensorflow.python.autograph.impl.api.StagingError: in converted code:

    ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:165 call
        num_routing=self.routings)
    ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:396 update_routing
        swap_memory=True)
    /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py:3501 while_loop
        return_same_structure)
    /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py:3012 BuildLoop
        pred, body, original_loop_vars, loop_vars, shape_invariants)
    /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py:2937 _BuildLoop
        body_result = body(*packed_vars_for_body)
    ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:377 _body
        tf.print("mean logit:", mean_logit, output_stream=sys.stdout)
    ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:377 _body
        tf.print("mean logit:", mean_logit, output_stream=sys.stdout)
    /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/bdb.py:51 trace_dispatch
        return self.dispatch_line(frame)
    /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/bdb.py:70 dispatch_line
        if self.quitting: raise BdbQuit

    BdbQuit: 


originally defined at:
  File "main_train_and_test_adam_opt.py", line 102, in initNetworks
    training_net = tf.make_template('net', self.network)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 160, in make_template
    **kwargs)

2019-12-18 14:28:18,905 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:12: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-12-18 14:28:18,906 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:16: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-12-18 14:28:19,052 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:18: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-12-18 14:28:19,054 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:19: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

2019-12-18 14:28:19,065 WARNING tensorflow From main_train_and_test_adam_opt.py:102: The name tf.make_template is deprecated. Please use tf.compat.v1.make_template instead.

2019-12-18 14:28:19,067 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/data_generator.py:22: The name tf.FIFOQueue is deprecated. Please use tf.queue.FIFOQueue instead.

2019-12-18 14:28:19,071 WARNING tensorflow From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-12-18 14:28:19,072 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/SegCaps.py:27: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
2019-12-18 14:28:19,159 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa644014ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa644014ef0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 14:28:19,249 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa63414e6d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa63414e6d8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 14:28:19,322 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa63414eb70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fa63414eb70>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-18 14:28:19,339 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7fa644014f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7fa644014f60>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-18 14:30:54,432 WARNING tensorflow From <stdin>:1: Print (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2018-08-20.
Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:
```python
    sess = tf.compat.v1.Session()
    with sess.as_default():
        tensor = tf.range(10)
        print_op = tf.print(tensor)
        with tf.control_dependencies([print_op]):
          out = tf.add(tensor, tensor)
        sess.run(out)
    ```
Additionally, to use tf.print in python 2.7, users must make sure to import
the following:

  `from __future__ import print_function`

2019-12-18 15:25:01,731 ERROR root Error at tf
Traceback (most recent call last):
  File "main_train_and_test_adam_opt.py", line 328, in <module>
    loop.run()
  File "./Lung_Segmentation/tensorflow_train/train_loop.py", line 206, in run
    self.init_all()
  File "./Lung_Segmentation/tensorflow_train/train_loop.py", line 134, in init_all
    self.initNetworks()
  File "main_train_and_test_adam_opt.py", line 109, in initNetworks
    prediction = training_net(data,num_labels=self.num_labels,is_training=True, data_format=self.data_format)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 392, in __call__
    return self._call_func(args, kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 354, in _call_func
    result = self._func(*args, **kwargs)
  File "./Lung_Segmentation/LungSeg/SegCaps/SegCaps.py", line 38, in SegCaps_multilabels
    routings=1, name='primarycaps',is_training=is_training)(conv1_reshaped)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 636, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 146, in wrapper
    ), args, kwargs)
tensorflow.python.autograph.impl.api.StagingError: in converted code:

    ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:165 call
        num_routing=self.routings)
    ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:391 update_routing
        i = tf.constant(0, dtype=tf.int32)
    ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:391 update_routing
        i = tf.constant(0, dtype=tf.int32)
    /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/bdb.py:51 trace_dispatch
        return self.dispatch_line(frame)
    /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/bdb.py:70 dispatch_line
        if self.quitting: raise BdbQuit

    BdbQuit: 


originally defined at:
  File "main_train_and_test_adam_opt.py", line 102, in initNetworks
    training_net = tf.make_template('net', self.network)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 160, in make_template
    **kwargs)

